### List all documents
GET http://ec2-3-145-169-99.us-east-2.compute.amazonaws.com/documents



### Sign up a new user
POST http://localhost:3001/users/signup
Content-Type: application/json

{
    "name": "David Eduardo Hernández García",
    "email": "dhernandez@blucapital.mx",
    "password": "asd",
    "role": "admin"
}
### Sign in a user
POST http://localhost:3001/users/signin
Content-Type: application/json

{
    "name": "Jesús Armando Rojas Gómez",
    "email": "dhernandez@blucapital.mx",
    "password": "asd"
}
###
POST http://ec2-18-224-54-81.us-east-2.compute.amazonaws.com:3000/users/signin
Content-Type: application/json

{
    "name": "Jesús Armando Rojas Gómez",
    "email": "dhernandez@blucapital.mx",
    "password": "asd"
}

### Get current user
GET http://localhost:3001/users/user
### Get all users
GET http://ec2-3-145-169-99.us-east-2.compute.amazonaws.com/users

### Sign out a user
POST http://localhost:3001/users/signout

### Change password 
POST http://localhost:3001/users/change-password
Content-Type: application/json

{
    "email": "test@blucapital.mx",
    "password": "123",
    "newPassword": "1234"
}